import { Component,OnInit} from '@angular/core';
import { DataService } from '../data.service';

@Component({
  selector: 'app-ludo',
  templateUrl: './ludo.component.html',
  styleUrls: ['./ludo.component.css']
})
export class LUDOComponent implements OnInit{
  path:any = "http://localhost:3000/uploads/";
  ludoBannerData:any;
  ludoGamesData:any;
  ludoRatingData:any;
  ludoGameToPlayData:any;
  ludoStepsData:any;
  ludoQueAnsData:any;
  footerCustomData:any;
  id:any=1;
  ludoReviewsData:any;


  constructor(private dataService:DataService){}


  ngOnInit(): void {
    this.getLudoBanner();
    this.getLudoGames();
    this.getLudoRating();
    this.getLudoGameToPlay();
    this.getFooterCustom();
    this.getLudoReviews();
    this.getLudoSteps();
    this.getQueAns();
    
  }
  questions=[
    {question:"Where can I play money winning games?",answer:"There are several online games where you can win cash. One way is through the Zupee money winning app. It is a mobile gaming app that allows users to play various games for real cash like Ludo, Snakes & Ladders, Trump Cards, and Tambola.  So, what are you waiting for? Play & put your skills to the test by competing for real cash on Zupee money app.",opened:false},
    {question:"Is it safe to play real money games on Zupee?",answer:"Yes, it is absolutely safe and legal to play real money games on Zupee. Download the Zupee money game app (Android APK/iOS) and play online cash games like Ludo, and Trump cards.",opened:false },
    {question:"Can I play online cash games and win real money on Zupee?",answer:"Yes. You can win actual cash by playing online cash games on Zupee. You can choose from multiple games based on your skills and win up to 10 lakhs. Instant withdrawal using various payment methods like bank transfer or UPI (Paytm, PhonePe, Google Pay) is available.",opened:false },
    {question:"Can I withdraw cash from money winning apps?",answer:"Yes. You can withdraw real cash from money winning apps like Zupee. Zupee offers instant and safe cash withdrawals from your wallet using UPI or a Bank account.",opened:false },
    {question:"Is it safe to add money to the online games wallet?",answer:"Yes, adding money to your game wallet is safe. Zupee has partnerships with the industry’s best, who ensure smooth and safe money transactions. You can add money using UPI, Bank account, Wallets, or Debit/Credit cards.",opened:false },
    {question:"How do online real cash games ensure fair play?",answer:"There are many ways in which the online money games on Zupee ensure fair play. One such measure is to get RNG certified. RNG certification ensures statistical randomness in the numbers generated by the elements like the dice in the game.",opened:false },
    {question:"How do online money games in India work?",answer:"To play real cash games on Zupee, players add money to their wallets and choose the tournament they would like to play. Once the tournament has enough people, the game begins. There are multiple formats to choose from based on a person’s interest and risk appetite. Every game has a prize pot that gets distributed at the end of the game based on the format one chooses to play. Players can instantly withdraw their cash winnings anytime. Learn about the pros of playing real cash games online. ",opened:false },
   ];
   toggleAns(question:any){
    console.log('Toggling answer for:', question.question);
    question.opened = !question.opened;
    console.log('New opened state:', question.opened);
     }

    //  ludoStepsData=[
    //   {steps:"STEP 1",heading:"CHOOSE ONLINE LUDO GAME FORMAT",image:"/assets/images/ludo_step1.webp"},
    //   {steps:"STEP 2",heading:"START THE ONLINE GAME",image:"/assets/images/ludo_step2.webp"},
    //   {steps:"STEP 3",heading:"CAPTURE TOKEN",image:"/assets/images/ludo_step3.webp"},
    //   {steps:"STEP 4",heading:"EARN MAXIMUM POINTS",image:"/assets/images/ludo_step4.webp"},
    //   {steps:"STEP 5",heading:"EARN EXTRA MOVES",image:"/assets/images/ludo_step5.webp"},
    //   {steps:"STEP 6",heading:"WIN THE GAME",image:"/assets/images/ludo_step6.webp"}
    //  ]

     getLudoBanner(){
      this.dataService.getLudoBannerData(this.id).subscribe(res=>{
        this.ludoBannerData = res;
      })
     }

     getLudoGames(){
      this.dataService.getLudoGamesData().subscribe(res=>{
        this.ludoGamesData = res;
      })
     }

     getLudoRating(){
      this.dataService.getLudoRatingData(this.id).subscribe(res=>{
        this.ludoRatingData = res;
      })
     }

     getLudoGameToPlay(){
      this.dataService.getLudoGameToPlayData(this.id).subscribe(res=>{
        this.ludoGameToPlayData = res;
      })
     }

     getLudoSteps(){
      this.dataService.getLudoStepsData().subscribe(res=>{
        this.ludoStepsData = res;
      })
     }
     getLudoGroups(){
      const reviewGroups = [];
      for (let i = 0; i < this.ludoStepsData.length; i += 3){
        reviewGroups.push(this.ludoStepsData.slice(i, i + 3));
      }
      return reviewGroups
    }
  
    getLudoGroups2(){
      const reviewGroups = [];
      for (let i = 0; i < this.ludoStepsData.length; i += 1){
        reviewGroups.push(this.ludoStepsData.slice(i, i + 1));
      }
      return reviewGroups
    }

     getFooterCustom(){
      this.dataService.getFooterCustomData(this.id).subscribe((res)=>{
        this.footerCustomData = res;
        console.log(this.footerCustomData)
      })
     }

     getLudoReviews(){
      this.dataService.getLudoReviewsData().subscribe((res)=>{
        this.ludoReviewsData = res;
        console.log(this.ludoReviewsData)
      })
     }
  
     getReviewGroups(){
      const reviewGroups = [];
      for (let i = 0; i < this.ludoReviewsData.length; i += 3){
        reviewGroups.push(this.ludoReviewsData.slice(i, i + 3));
      }
      return reviewGroups
    }
  
    getReviewGroups2(){
      const reviewGroups = [];
      for (let i = 0; i < this.ludoReviewsData.length; i += 1){
        reviewGroups.push(this.ludoReviewsData.slice(i, i + 1));
      }
      return reviewGroups
    }

    getQueAns(){
      this.dataService.getLudoQueAnsData().subscribe((res)=>{
        this.ludoQueAnsData = res;
        console.log(this.ludoQueAnsData)
      })
    }
}
